name: schedulemancer
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  nyxx: ^6.3.0
  nyxx_commands: ^6.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

assets:
  - .env